spring:
  datasource: 
    url: jdbc:postgresql://localhost:5432/orders
    driver-class-name: org.postgresql.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  database: postgresql
  
